name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKERHUB_USER_JUANDA}}
        DOCKER_PASS: ${{secrets.DOCKERHUB_PASS_JUANDA}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASS
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag juanda0/pokeneas-express:latest
      
    - name: Docker Push
      run: docker push juanda0/pokeneas-express

